server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone:
        http://zhusong:1234@localhost:8761/eureka/,http://zhusong:1234@localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: autodeliver
spring:
  profiles:
    dev
  application:
    name: service-autodeliver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geyinledi/my-configs.git
          username: 260221580@qq.com
          password: zhong173475
          search-paths:
            - my-configs
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接⼝的细节
  endpoint:
    health:
      show-details: always
test: youknow
